### ISSUE TITLE
the status of Open a pull request on Github can not updated

### ISSUE THREAD

**Issue by scottwansz** [learn-co-curriculum/oo-tic-tac-toe#12]
the status of Open a pull request on Github can not updated even I submitted succeed:

➜  oo-tic-tac-toe-002 git:(master) learn submit
Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
Submitting lesson...
Done.
➜  oo-tic-tac-toe-002 git:(master)

**Comment by AnnJohn** [comment]
Hi @scottwan sorry for the delay but for immediate help with this problem, please use the Ask a Question tool in Learn and someone from our Learn support team will get back to you right away. Thanks!
