### ISSUE TITLE
Not prompted to apply

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/oo-tic-tac-toe#15]
Hello,

After completing OO Tic Tac Toe (prelim work) and submitting, I don't seem to get an option for next steps.  I'm wondering if anyone can look into this and let me know what the options are.  All tests have been submitted and the "Track Complete" button is just greyed out and unclickable.

**Comment by AnnJohn** [comment]
Hi @bmolina-nyc sorry about this. We'll look into it and have someone get in touch with you. Thanks!

**Comment by AnnJohn** [comment]
Hi @bmolina-nyc it looks like there were some issues with the specific track you were on, but we've resolved the issue and you should be all set. Thanks!
