### ISSUE TITLE
Lessons

### ISSUE THREAD

**Issue by avanover0311** [learn-co-curriculum/oo-tic-tac-toe#21]
I have completed my Intro to Ruby and Object orientation lessons- but for whatever reason I don't see where I can move on. It is keeping on those lessons that I have already completed

**Comment by AnnJohn** [comment]
hi @avanover0311 sorry for the delay here. Since this is a space that we use for issues related to the content of lessons, the best way for you to get help with your problem is by emailing support@learn.co 

Thanks!
