### ISSUE TITLE
The test 'defines a constant WIN_COMBINATIONS with arrays for each win combination' too specific

### ISSUE THREAD

**Issue by peterberwind** [learn-co-curriculum/oo-tic-tac-toe#23]
Error Feedback:
 1) ./lib/tic_tac_toe.rb TicTacToe WIN_COMBINATIONS defines a constant WIN_COMBINATIONS with arrays for each win combination
     Failure/Error: expect(TicTacToe::WIN_COMBINATIONS).to include([6,4,2])
       expected [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]] to include [6, 4, 2]
     # ./spec/01_tic_tac_toe_spec.rb:51:in `block (4 levels) in <top (required)>'

Issue:
[2,4,6] is the same as [6,4,2]. The test 'defines a constant WIN_COMBINATIONS with arrays for each win combination' is too specific and doesn't account for potential variations in array value orders.

**Comment by gj** [comment]
Fixed in #20. Thanks @peterberwind !
