### ISSUE TITLE
The new Learn IDE cannot open this lesson. 

### ISSUE THREAD

**Issue by talgoldfus** [learn-co-curriculum/oo-tic-tac-toe#24]
After installing the Lear IDE this lesson does not open properly anymore .

Thats the error message i get :

s/oo-tic-tac-toe-q-000/.learn (Errno::ENOENT)                                   
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-open-1.1.59/lib/learn_ope
n/opener.rb:232:in `ios_lesson?'                                                
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-open-1.1.59/lib/learn_ope
n/opener.rb:297:in `bundle_install'                                             
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-open-1.1.59/lib/learn_ope
n/opener.rb:33:in `run'                                                         
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-open-1.1.59/lib/learn_ope
n/opener.rb:7:in `run'                                                          
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-open-1.1.59/bin/learn-ope
n:7:in `<top (required)>'                                                       
        from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-open:23:in `load'         
        from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-open:23:in `<main>'       
        from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eva
l'                                                                              
        from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<ma
in>'

**Comment by AnnJohn** [comment]
sorry for the huge delay with this @talgoldfus but if this is still an issue, could you please file a bug report for this? thanks!
