### ISSUE TITLE
#won? requirements are contradicting compared to spec test in 01_tic_tac_toe_spec.rb

### ISSUE THREAD

**Issue by DTF919** [learn-co-curriculum/oo-tic-tac-toe#29]
On the website we are asked to have the #won? method to return the winning combination as an array. However in 01_tic_tac_toe_spec.rb the test for a win is expecting a boolean value of "true." For my submission I edited the spec file and copied the code from game_status_spec.rb  located in ttt-game-status-ruby-intro-000\spec for the #won? method's win tests for this project.

Regardless of which one was wanted, it should be corrected as it can be confusing.

Thanks for taking the time to read this.

**Comment by aturkewi** [comment]
Fixed in PR #33
