### ISSUE TITLE
Turn Method

### ISSUE THREAD

**Issue by SCDesigns** [learn-co-curriculum/oo-tic-tac-toe#30]
The tests call for the board to be displayed once but the solution displays the board twice.

  def turn
    display_board
    puts "Please enter 1-9:"
    input = gets.strip
    if !valid_move?(input)
      turn
    end
    move(input, current_player)
    display_board
  end

Corresponding error message: 

Failures:                                                                                                                       

  1) ./lib/tic_tac_toe.rb TicTacToe#turn makes valid moves and displays the board  
     Failure/Error: expect(game).to receive(:display_board)  
       (#TicTacToe:0x00000001ce98d8).display_board(*(any args))  
           expected: 1 time with any arguments  
           received: 2 times with any arguments  
     # ./spec/01_tic_tac_toe_spec.rb:109:in `block (4 levels) in <top (required)>'

**Comment by aturkewi** [comment]
Fixed in PR #33
