### ISSUE TITLE
02_play_spec.rb - Puts Cat's Game 

### ISSUE THREAD

**Issue by alpay** [learn-co-curriculum/oo-tic-tac-toe#37]
In the early lesson's we puts **"Cats Game"** if the game is draw, but in OO Tic Tac Toe lesson, spec wants us to write **"Cat's Game"**.  It's a really minor _typo_ but you may want to change it. 

Thank you.

**Comment by gj** [comment]
Hi @mangoser !

`Cat's Game` is correct — feel free to make a PR against any lessons that refer to `Cats Game`. 🙂
