### ISSUE TITLE
Missing Rakefile?

### ISSUE THREAD

**Issue by TyJaYo** [learn-co-curriculum/oo-tic-tac-toe#41]
The readme mentions a Rakefile, but it does not appear in the actual project structure. I wouldn't mind being able to run `rake console` like I could in a previous lesson.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
