### ISSUE TITLE
Test for #winner uses impossible games

### ISSUE THREAD

**Issue by TyJaYo** [learn-co-curriculum/oo-tic-tac-toe#42]
Here is the test for `#winner`:
```ruby
    describe '#winner' do
      it 'return X when X won' do
        game = TicTacToe.new
        board = ["X", " ", " ", " ", "X", " ", " ", " ", "X"]
        game.instance_variable_set(:@board, board)

        expect(game.winner).to eq("X")
      end

      it 'returns O when O won' do
        game = TicTacToe.new
        board = ["X", "O", " ", " ", "O", " ", " ", "O", "X"]
        game.instance_variable_set(:@board, board)

        expect(game.winner).to eq("O")
      end

      it 'returns nil when no winner' do
        game = TicTacToe.new
        board = ["X", "O", " ", " ", " ", " ", " ", "O", "X"]
        game.instance_variable_set(:@board, board)

        expect(game.winner).to be_nil
      end
```

Only the "no winner" portion of this test uses a board that could occur during legal play. The unfortunate effect of this is that there exist creative solutions which will display the winner correctly 100% of the time the game is played, but still not pass this test. Here is an example:

```ruby
  def winner
    turn_count % 2 == 0 ? "O" : "X" if won?
  end
```

It's the reverse of `#current_player`, and that's by design. If the game board shows a win and it's your turn, you just lost! I know there are many ways to code `#winner` so that it displays the type of token in the winning positions, it was just disappointing to see a working solution fail the test for no good reason.

If you agree that there is no harm to the test using possible game boards, you are welcome to use my edited version of the test:
```ruby
    describe '#winner' do
      it 'return X when X won' do
        game = TicTacToe.new
        board = ["X", "O", "O", " ", "X", " ", " ", " ", "X"]
        game.instance_variable_set(:@board, board)

        expect(game.winner).to eq("X")
      end

      it 'returns O when O won' do
        game = TicTacToe.new
        board = ["X", "O", "X", " ", "O", " ", " ", "O", "X"]
        game.instance_variable_set(:@board, board)

        expect(game.winner).to eq("O")
      end

      it 'returns nil when no winner' do
        game = TicTacToe.new
        board = ["X", "O", " ", " ", " ", " ", " ", "O", "X"]
        game.instance_variable_set(:@board, board)

        expect(game.winner).to be_nil
      end
    end
```

The parts of the test for `#play` that rely on determining a winner from an impossible board would need tweaking as well:
```ruby
describe '#play' do
#...
      it 'congratulates the winner X' do
        game = TicTacToe.new
        board = ["X", "X", "X", "O", "O", " ", " ", " ", " "]
        game.instance_variable_set(:@board, board)
        allow($stdout).to receive(:puts)

        expect($stdout).to receive(:puts).with("Congratulations, X!")

        game.play
      end

      it 'congratulates the winner O' do
        game = TicTacToe.new
        board = ["X", "X", " ", "X", " ", " ", "O", "O", "O"]
        game.instance_variable_set(:@board, board)

        allow($stdout).to receive(:puts)

        expect($stdout).to receive(:puts).with("Congratulations, O!")

        game.play
      end
#...
end
```
(snuck in some grammar fixes for the congratulation messages too ;)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
