### ISSUE TITLE
CLI code already done when forked lab

### ISSUE THREAD

**Issue by pmknyc** [learn-co-curriculum/oo-tic-tac-toe#43]
9/13/18 4:15pm
Heads up that when I forked this lab today using local IDE, the ./bin/tictactoe 
file already contained the "answer" code as requested in lab instructions.

**Comment by cjbrock** [comment]
Thanks @pmknyc! We rebased on solution a little while ago and missed that one. I fixed it now.

// <3 Corinna

**Comment by pmknyc** [comment]
Great! Glad to help.
