### ISSUE TITLE
Purely object-oriented code not passing

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/oo-tic-tac-toe#9]
Code written in purely object-oriented style will not pass 3 tests, because in 3 places the spec invokes the methods passing in arguments. Should/could be adjusted?

**Comment by aviflombaum** [comment]
This is incorrect or I'm not seeing that and the solution branch is passing.

Can the student that brought this up join the issue? And we should make them raise issues so we can ask more questions - lets try not to raise on behalf.

**Comment by mendelB** [comment]
I assume this was fixed as all the tests seem to not be using `board` arguments and utilizing the `@board` variable which I imagine was the issue here? Either way major fixes were made since then so we should be all clear on this issue 😺
